DROP TABLE IF EXISTS "DIRECT_REPORTS" CASCADE;
DROP TABLE IF EXISTS "EMPLOYEES" CASCADE;


create table DIRECT_REPORTS (
       manager_id integer not null,
        employee_id integer
    );

create table EMPLOYEES (
       id integer generated by default as identity,
        active boolean not null,
        hire_date date not null,
        name varchar(255) not null,
        position varchar(255) not null,
        primary key (id)
    );

 alter table DIRECT_REPORTS 
       add constraint FKmq3x5uh6cpnmion6w5bka04le 
       foreign key (manager_id) 
       references EMPLOYEES;